import "dotenv/config";
import { PrismaBetterSqlite3 } from "@prisma/adapter-better-sqlite3";
import { PrismaClient } from "../generated/prisma/client.ts";

const adapter = new PrismaBetterSqlite3({ url: process.env.DATABASE_URL });
const prisma = new PrismaClient({ adapter });

const SETS = {
  Activities: [
    { english: "hobbies", dutch: "hobby's" },
    { english: "to play the piano", dutch: "piano spelen" },
    { english: "to listen to music", dutch: "muziek luisteren" },
    { english: "to watch a movie", dutch: "film kijken" },
    { english: "to play football", dutch: "voetballen" },
    { english: "sports", dutch: "sporten" },
    { english: "volleyball", dutch: "volleybal" },
    { english: "skiing", dutch: "skiën" },
    { english: "tennis", dutch: "tennis" },
    { english: "hockey", dutch: "hockey" },
    { english: "horse-riding", dutch: "paardrijden" },
    { english: "boxing", dutch: "boksen" },
    { english: "skating", dutch: "schaatsen" },
    { english: "swimming", dutch: "zwemmen" },
    { english: "verbs", dutch: "werkwoorden" },
    { english: "to look", dutch: "kijken" },
    { english: "to go", dutch: "gaan" },
    { english: "will", dutch: "zal" },
    { english: "made", dutch: "maakte" },
    { english: "to do", dutch: "doen" },
    { english: "came", dutch: "kwam" },
    { english: "called", dutch: "genoemd" },
    { english: "asked", dutch: "gevraagd" },
    { english: "saw", dutch: "zag" },
    { english: "to make", dutch: "maken" },
    { english: "jobs", dutch: "banen" },
    { english: "journalist", dutch: "journalist" },
    { english: "teacher", dutch: "leerkracht" },
    { english: "dentist", dutch: "tandarts" },
    { english: "plumber", dutch: "loodgieter" },
    { english: "doctor", dutch: "dokter" },
    { english: "carpenter", dutch: "timmerman" },
  ],
  Animals: [
    { english: "to feed the cat", dutch: "de kat eten geven" },
    { english: "to walk the dog", dutch: "de hond uitlaten" },
    { english: "to protect", dutch: "beschermen" },
    { english: "to fly", dutch: "vliegen" },
    { english: "to jump", dutch: "springen" },
    { english: "to swim", dutch: "zwemmen" },
    { english: "to be", dutch: "zijn" },
    { english: "I am", dutch: "ik ben" },
    { english: "you are", dutch: "jij bent" },
    { english: "he/she/it is", dutch: "hij/zij/het is" },
    { english: "we are", dutch: "wij zijn" },
    { english: "you are", dutch: "jullie zijn" },
    { english: "they are", dutch: "zij zijn" },
    { english: "monkey", dutch: "aap" },
    { english: "spider", dutch: "spin" },
    { english: "crab", dutch: "krab" },
    { english: "birds", dutch: "vogels" },
    { english: "lizard", dutch: "hagedis" },
    { english: "crocodile", dutch: "krokodil" },
    { english: "snake", dutch: "slang" },
    { english: "elephant", dutch: "olifant" },
    { english: "mouse", dutch: "muis" },
    { english: "mice", dutch: "muizen" },
    { english: "owl", dutch: "uil" },
    { english: "eagle", dutch: "arend" },
    { english: "goose", dutch: "gans" },
    { english: "geese", dutch: "ganzen" },
    { english: "fish", dutch: "vissen" },
    { english: "fly", dutch: "vlieg" },
    { english: "ladybug", dutch: "lieveheersbeestje" },
    { english: "bee", dutch: "bij" },
    { english: "butterfly", dutch: "vlinder" },
    { english: "butterflies", dutch: "vlinders" },
    { english: "caterpillar", dutch: "rups" },
    { english: "cockroach", dutch: "kakkerlak" },
    { english: "grasshopper", dutch: "sprinkhaan" },
    { english: "beetle", dutch: "kever" },
    { english: "ant", dutch: "mier" },
    { english: "wasp", dutch: "wesp" },
    { english: "tick", dutch: "teek" },
    { english: "creature", dutch: "wezen" },
    { english: "humans", dutch: "mensen" },
  ],
  Creativity: [
    { english: "to make", dutch: "maken" },
    { english: "I make", dutch: "ik maak" },
    { english: "he/she/it makes", dutch: "hij/zij/het maakt" },
    { english: "we make", dutch: "wij maken" },
    { english: "you make", dutch: "jullie maken" },
    { english: "they make", dutch: "zij maken" },
    { english: "made by", dutch: "gemaakt door" },
    { english: "I made", dutch: "ik maakte" },
    { english: "to create", dutch: "creëren" },
    { english: "to think", dutch: "denken" },
    { english: "to write", dutch: "schrijven" },
    { english: "to paint", dutch: "schilderen" },
    { english: "art", dutch: "kunst" },
    { english: "brush", dutch: "kwast" },
    { english: "to paint", dutch: "schilderen" },
    { english: "scissors", dutch: "schaar" },
    { english: "paper", dutch: "papier" },
    { english: "thinking", dutch: "nadenken" },
    { english: "creativity", dutch: "creativiteit" },
    { english: "magic", dutch: "magie" },
    { english: "something", dutch: "iets" },
    { english: "someone", dutch: "iemand" },
    { english: "presentation", dutch: "presentatie" },
    { english: "experiments", dutch: "experimenten" },
    { english: "research", dutch: "onderzoek" },
    { english: "researcher", dutch: "onderzoeker" },
    { english: "poem", dutch: "gedicht" },
    { english: "fantasy", dutch: "fantasie" },
    { english: "actor", dutch: "acteur" },
    { english: "actress", dutch: "actrice" },
  ],
  Earth: [
    { english: "climate", dutch: "klimaat" },
    { english: "temperature", dutch: "temperatuur" },
    { english: "weather", dutch: "weer" },
    { english: "30 degrees Celsius", dutch: "30 graden Celsius" },
    { english: "geography", dutch: "aardrijkskunde" },
    { english: "earth", dutch: "aarde" },
    { english: "global warming", dutch: "opwarming van de aarde" },
    { english: "climate change", dutch: "klimaatverandering" },
    { english: "rainforest", dutch: "regenwoud" },
    { english: "earthquake", dutch: "aardbeving" },
    { english: "environment", dutch: "milieu" },
    { english: "surroundings", dutch: "omgeving" },
    { english: "wood", dutch: "hout" },
    { english: "mountains", dutch: "bergen" },
    { english: "landscape", dutch: "landschap" },
    { english: "capital", dutch: "hoofdstad" },
    { english: "village", dutch: "dorp" },
    { english: "beach", dutch: "strand" },
    { english: "city", dutch: "stad" },
    { english: "hill", dutch: "heuvel" },
    { english: "forest", dutch: "woud" },
    { english: "river", dutch: "rivier" },
    { english: "to use", dutch: "gebruiken" },
    { english: "to think", dutch: "denken" },
    { english: "to need", dutch: "nodig hebben" },
    { english: "to happen", dutch: "gebeuren" },
    { english: "to continue", dutch: "doorgaan" },
    { english: "to increase", dutch: "toenemen" },
    { english: "I think", dutch: "ik denk" },
    { english: "you think", dutch: "jij denkt" },
    { english: "he/she/it thinks", dutch: "hij/zij/het denkt" },
    { english: "we think", dutch: "wij denken" },
    { english: "you think", dutch: "jullie denken" },
    { english: "they think", dutch: "zij denken" },
  ],
  People: [
    { english: "aunt", dutch: "tante" },
    { english: "brother", dutch: "broer" },
    { english: "cousin", dutch: "neef/nicht" },
    { english: "daughter", dutch: "dochter" },
    { english: "father", dutch: "vader" },
    { english: "granddaughter", dutch: "kleindochter" },
    { english: "grandmother", dutch: "oma" },
    { english: "grandson", dutch: "kleinzoon" },
    { english: "mother", dutch: "moeder" },
    { english: "nephew", dutch: "neefje" },
    { english: "niece", dutch: "nichtje" },
    { english: "sister", dutch: "zus" },
    { english: "son", dutch: "zoon" },
    { english: "stepdaughter", dutch: "stiefdochter" },
    { english: "stepmother", dutch: "stiefmoeder" },
    { english: "stepson", dutch: "stiefzoon" },
    { english: "uncle", dutch: "oom" },
    { english: "back", dutch: "rug" },
    { english: "cheeks", dutch: "wangen" },
    { english: "chest", dutch: "borst" },
    { english: "chin", dutch: "kin" },
    { english: "ears", dutch: "oren" },
    { english: "eyebrows", dutch: "wenkbrauwen" },
    { english: "eyes", dutch: "ogen" },
    { english: "feet", dutch: "voeten" },
    { english: "fingers", dutch: "vingers" },
    { english: "foot", dutch: "voet" },
    { english: "forehead", dutch: "voorhoofd" },
    { english: "hair", dutch: "haar" },
    { english: "hands", dutch: "handen" },
    { english: "head", dutch: "hoofd" },
    { english: "hips", dutch: "heupen" },
    { english: "knees", dutch: "knieën" },
    { english: "legs", dutch: "benen" },
    { english: "lips", dutch: "lippen" },
    { english: "mouth", dutch: "mond" },
    { english: "neck", dutch: "nek" },
    { english: "nose", dutch: "neus" },
    { english: "shoulders", dutch: "schouders" },
    { english: "stomach", dutch: "maag" },
    { english: "teeth", dutch: "tanden" },
    { english: "throat", dutch: "keel" },
    { english: "toes", dutch: "tenen" },
    { english: "tongue", dutch: "tong" },
    { english: "tooth", dutch: "tand" },
    { english: "waist", dutch: "middel, taille" },
  ],
};

const GROUP = "Groep 7";

async function main() {
  for (const [name, pairs] of Object.entries(SETS)) {
    const pack = await prisma.wordPack.upsert({
      where: { name_group: { name, group: GROUP } },
      update: {},
      create: { name, group: GROUP },
    });
    await prisma.wordPair.deleteMany({ where: { packId: pack.id } });
    await prisma.wordPair.createMany({
      data: pairs.map((p) => ({ packId: pack.id, english: p.english, dutch: p.dutch })),
    });
    console.log(`Seeded ${pairs.length} paren voor pakket "${name}" (${GROUP})`);
  }
}

main()
  .then(() => prisma.$disconnect())
  .catch((err) => {
    console.error(err);
    prisma.$disconnect();
    process.exit(1);
  });
